# Generated by Django 5.1.7 on 2025-03-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='image')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='date_of_creation')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='last_modified_date')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
